language: c
compiler:
  - gcc
env:	
  - CTEST_MODEL=Experimental
#  - CTEST_MODEL=Nightly
branches:
  only:
    - master
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make
  - ctest